### ISSUE TITLE
own data saving system + registry events

### ISSUE THREAD

**Issue by C0LiSii0N** [Hennamann/Wasteland#10]
Hey I asked help on the minecraftforge forum with a link to your code asking for help to fix the multiplayer problem and a guy aswered me, I think you should look at the thread! : http://www.minecraftforge.net/forum/topic/64082-unable-to-find-spawn-biome/

**Comment by Hennamann** [comment]
I honestly agree with him, the code is a mess. I ported the code, I never actually wrote it, but I have no intention of rewriting it unless I absolutely need to. I haven't had the time to look into the issue in question but it should be an easy fix, I just need the time to do it. life's been keeping me busy

**Comment by C0LiSii0N** [comment]
Well, if fixing those things can fix the multiplayer problem, everyone will be happy! :D

**Comment by Hennamann** [comment]
The multiplayer problems should now be fixed in the latest release. There are of course still a lot of things that need fixing and cleanup as per the forum thread linked above, but that will have to wait for another time. Closing this issue.
