### ISSUE TITLE
Update Curseforge Page?

### ISSUE THREAD

**Issue by temp1011** [Hennamann/Wasteland#11]
Hi, 
There was an issue with the mod that caused crashes on world load that was fixed in https://github.com/Hennamann/Wasteland/commit/8f1998669a32081374dea59f0b91c524f27b25da. Unfortunately this fix made it to maven but not to curseforge.

Would it be possible to release version 1.2.2-11 on curseforge? It's the most prominent place to get the mod from and the current version causes issues (see https://github.com/ForestryMC/ForestryMC/issues/2116).

**Comment by Hennamann** [comment]
This has been done, sorry about the delay in doing so.
