### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [Hennamann/Wasteland#15]
When trying to start my server, I receive this crash: https://pastebin.com/ZUNs5zzG
I have tried going on[ this website ](https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/Wastelands-1.12-1.2.2-11-universal.jar)to download the version that seems to have helped people with similar issues, but the website is unavailable for me and I am unable to find another way to download the new version.

Please help.

**Comment by Hennamann** [comment]
Lates version on curseforge fixes this
