### ISSUE TITLE
Does not work on a server as of Dec. 12th, 2019.

### ISSUE THREAD

**Issue by sirrobindoger** [Hennamann/Wasteland#20]
Using `level-type=Wasteland`, the world doesn't generate the wasteland-reborn on the server, or if it does, clients are unable to join it. Spits out a lot of errors too.

Steps to reproduce:
Download the latest version of it from curseforge (1.12.2) and run it on your own MC server and try to join.

**Comment by Hennamann** [comment]
This should be fixed in the latest release here on Github and on Curse, closing.
