### ISSUE TITLE
 Exception getting block type in world

### ISSUE THREAD

**Issue by Phan7om012** [Hennamann/Wasteland#23]
Crash only appears when I tried to load a wasteland world type pls help me !!

[crash-2021-02-06_18.04.49-server.txt](https://github.com/Hennamann/Wasteland/files/5937380/crash-2021-02-06_18.04.49-server.txt)

**Comment by Hennamann** [comment]
This error is from a minecraft version earlier than 1.11. This repository is only for wasteland version 1.11 and 1.12.
Can't really help you with this one...
