### ISSUE TITLE
[1.12.2] Crash in singleplayer

### ISSUE THREAD

**Issue by MarioSMB** [Hennamann/Wasteland#7]
Loading a new Wasteland world causes the following crash (Exception initializing level):

https://pastebin.com/nuv7jkwW

**Comment by Hennamann** [comment]
Hmmm, looks like Wasteland is posting to a Forge event, causing unexpected issues in Biomes o Plenty. should be an easy fix.

**Comment by Hennamann** [comment]
I have not tested but it should work, here's another alpha build for you to test: https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/Wastelands-1.12-1.2.2-11-universal.jar If it works I'll get it pushed to Curse ASAP this time.

**Comment by MarioSMB** [comment]
That indeed fixed it, thanks again.
